// quasar/arbitration-art-q/src/components/bots/SpreadHistoryDialog.vue
<template>
  <q-dialog :model-value="modelValue" @update:model-value="v => emit('update:modelValue', v)" maximized transition-show="slide-up" transition-hide="slide-down">
    <q-card class="bg-dark text-text-color column">
      <q-card-section class="row items-center justify-between head-bar border-bottom-dark q-pa-md">
        <div class="text-h6 text-title-color text-weight-bold">
          История спреда: <span class="text-primary">{{ bot?.coin }}</span>
        </div>
        <q-btn icon="close" flat round dense v-close-popup color="grey-5" />
      </q-card-section>
      
      <q-card-section class="col full-height q-pa-none relative-position">
        <div v-if="loading" class="flex flex-center full-height opacity-70">
          <q-spinner size="lg" color="primary" class="q-mr-sm"/> Загрузка исторических данных...
        </div>
        <div v-if="error" class="flex flex-center full-height text-negative">{{ error }}</div>
        
        <div ref="chartContainer" class="chart-container" :class="{ 'hidden': loading || error }"></div>
        
        <div v-if="!loading && !error" class="legend-panel">
          <div class="legend-item"><span class="legend-color bg-positive"></span> Open Spread</div>
          <div class="legend-item"><span class="legend-color bg-negative"></span> Close Spread</div>
        </div>
      </q-card-section>
    </q-card>
  </q-dialog>
</template>

<script setup lang="ts">
import { ref, watch, onUnmounted, nextTick } from 'vue';
import { createChart, type IChartApi, type ISeriesApi, ColorType } from 'lightweight-charts';
import type { BotConfig } from 'src/services/api/botConfig';
import { binanceApi } from 'src/services/exchanges/binanceApi';
import { mexcApi } from 'src/services/exchanges/mexcApi';

const props = defineProps<{
  modelValue: boolean;
  bot: BotConfig | null;
}>();

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void;
}>();

const chartContainer = ref<HTMLElement | null>(null);
const loading = ref(false);
const error = ref('');

let chart: IChartApi | null = null;
let openSeries: ISeriesApi<'Line'> | null = null;
let closeSeries: ISeriesApi<'Line'> | null = null;

const initChart = () => {
  if (!chartContainer.value) return;
  if (chart) {
    chart.remove();
  }

  chart = createChart(chartContainer.value, {
    layout: {
      background: { type: ColorType.Solid, color: 'transparent' },
      textColor: 'rgba(255, 255, 255, 0.7)',
    },
    grid: {
      vertLines: { color: 'rgba(255, 255, 255, 0.05)' },
      horzLines: { color: 'rgba(255, 255, 255, 0.05)' },
    },
    rightPriceScale: {
      borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    timeScale: {
      borderColor: 'rgba(255, 255, 255, 0.1)',
      timeVisible: true,
      secondsVisible: false,
    },
    autoSize: true,
  });

  openSeries = chart.addLineSeries({
    color: '#4caf50',
    lineWidth: 2,
    priceLineVisible: false,
  });

  closeSeries = chart.addLineSeries({
    color: '#f44336',
    lineWidth: 2,
    priceLineVisible: false,
  });
};

const loadHistory = async () => {
  if (!props.bot) return;
  loading.value = true;
  error.value = '';

  try {
    const limitParams = 60 * 6; // last 6 hours based on 1m klines
    
    let pkPromise, skPromise;
    
    if (props.bot.primary_exchange === 'binance_futures') pkPromise = binanceApi.getKlines(props.bot.coin, limitParams);
    else pkPromise = mexcApi.getKlines(props.bot.coin, limitParams);

    if (props.bot.secondary_exchange === 'mexc_futures') skPromise = mexcApi.getKlines(props.bot.coin, limitParams);
    else skPromise = binanceApi.getKlines(props.bot.coin, limitParams);

    const [primaryKlines, secondaryKlines] = await Promise.all([pkPromise, skPromise]);

    const openData = [];
    const closeData = [];
    const pMap = new Map();
    primaryKlines.forEach(k => pMap.set(k.timestamp, k.close));
    
    for (const sk of secondaryKlines) {
      const pkClose = pMap.get(sk.timestamp);
      if (pkClose !== undefined) {
        const openS = ((pkClose - sk.close) / sk.close) * 100;
        const closeS = ((sk.close - pkClose) / pkClose) * 100;
        
        // TradingView requires Unix timestamp in seconds
        const time = Math.floor(sk.timestamp / 1000) as any;
        
        openData.push({ time, value: openS });
        closeData.push({ time, value: closeS });
      }
    }

    openData.sort((a,b) => a.time - b.time);
    closeData.sort((a,b) => a.time - b.time);

    await nextTick();
    if (!chart) initChart();
    
    openSeries?.setData(openData);
    closeSeries?.setData(closeData);
    chart?.timeScale().fitContent();
    
  } catch (err) {
    console.error(err);
    error.value = 'Не удалось загрузить историю!';
  } finally {
    loading.value = false;
  }
};

watch(() => props.modelValue, (val) => {
  if (val) {
    nextTick(() => {
      initChart();
      loadHistory();
    });
  } else {
    if (chart) {
      chart.remove();
      chart = null;
    }
  }
});

onUnmounted(() => {
  if (chart) chart.remove();
});
</script>

<style lang="sass" scoped>
.head-bar
  height: 64px
  
.border-bottom-dark
  border-bottom: 1px solid $blue-dark

.chart-container
  width: 100%
  height: 100%
  
.hidden
  display: none

.legend-panel
  position: absolute
  top: 10px
  left: 20px
  display: flex
  flex-direction: column
  gap: 4px
  z-index: 10
  font-size: 13px
  opacity: 0.8
  font-weight: 500

.legend-item
  display: flex
  align-items: center
  gap: 8px

.legend-color
  width: 12px
  height: 3px
  display: inline-block
  border-radius: 2px
</style>

// arbitration-art-ui/src/app/features/bots/spread-history-dialog.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  OnDestroy,
  inject,
  input,
  output,
  signal,
  viewChild,
  AfterViewInit,
} from '@angular/core';
import {
  createChart,
  LineSeries,
  ColorType,
  type IChartApi,
  type ISeriesApi,
  type Time,
} from 'lightweight-charts';

import { DecimalPipe } from '@angular/common';

import { BotConfig } from '../../core/services/bot-config.service';
import {
  SpreadHistoryService,
  SpreadHistoryPoint,
} from '../../core/services/spread-history.service';

const EXCHANGE_LABELS: Record<string, string> = {
  binance_futures: 'Binance',
  mexc_futures: 'MEXC',
};

@Component({
  selector: 'app-spread-history-dialog',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DecimalPipe],
  templateUrl: './spread-history-dialog.component.html',
  styleUrl: './spread-history-dialog.component.scss',
})
export class SpreadHistoryDialogComponent implements AfterViewInit, OnDestroy {
  private readonly spreadHistory = inject(SpreadHistoryService);

  readonly bot = input.required<BotConfig>();
  readonly closed = output<void>();

  readonly chartContainer =
    viewChild.required<ElementRef<HTMLDivElement>>('chartContainer');

  readonly loading = signal(true);
  readonly error = signal<string | null>(null);
  readonly pointCount = signal(0);

  /** Labels for display in the template */
  readonly primaryLabel = computed(
    () => EXCHANGE_LABELS[this.bot().primary_exchange] || this.bot().primary_exchange,
  );
  readonly secondaryLabel = computed(
    () => EXCHANGE_LABELS[this.bot().secondary_exchange] || this.bot().secondary_exchange,
  );

  private chart: IChartApi | null = null;
  private openSpreadSeries: ISeriesApi<'Line'> | null = null;
  private closeSpreadSeries: ISeriesApi<'Line'> | null = null;

  ngAfterViewInit(): void {
    this.initChart();
    this.loadData();
  }

  ngOnDestroy(): void {
    this.chart?.remove();
  }

  close(): void {
    this.closed.emit();
  }

  onBackdropClick(event: MouseEvent): void {
    if ((event.target as HTMLElement).classList.contains('dialog-backdrop')) {
      this.close();
    }
  }

  onBackdropKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.close();
    }
  }

  private initChart(): void {
    const container = this.chartContainer().nativeElement;

    this.chart = createChart(container, {
      layout: {
        background: { type: ColorType.Solid, color: 'transparent' },
        textColor: 'rgba(255, 255, 255, 0.5)',
        fontSize: 11,
      },
      grid: {
        vertLines: { color: 'rgba(255, 255, 255, 0.04)' },
        horzLines: { color: 'rgba(255, 255, 255, 0.04)' },
      },
      crosshair: {
        vertLine: { color: 'rgba(255, 255, 255, 0.15)' },
        horzLine: { color: 'rgba(255, 255, 255, 0.15)' },
      },
      timeScale: {
        borderColor: 'rgba(255, 255, 255, 0.08)',
        timeVisible: true,
        secondsVisible: false,
      },
      rightPriceScale: {
        borderColor: 'rgba(255, 255, 255, 0.08)',
      },
      autoSize: true,
    });

    const primaryName = this.primaryLabel();
    const secondaryName = this.secondaryLabel();

    // Open: sell on primary, buy on secondary
    this.openSpreadSeries = this.chart.addSeries(LineSeries, {
      color: '#4caf50',
      lineWidth: 2,
      title: `${primaryName} → ${secondaryName}`,
      priceFormat: { type: 'price', precision: 3, minMove: 0.001 },
    });

    // Close: sell on secondary, buy on primary
    this.closeSpreadSeries = this.chart.addSeries(LineSeries, {
      color: '#ef5350',
      lineWidth: 2,
      title: `${secondaryName} → ${primaryName}`,
      priceFormat: { type: 'price', precision: 3, minMove: 0.001 },
    });
  }

  private loadData(): void {
    this.loading.set(true);
    this.error.set(null);
    const bot = this.bot();

    this.spreadHistory
      .loadHistory(bot.coin, bot.primary_exchange, bot.secondary_exchange)
      .subscribe({
        next: (points) => {
          this.pointCount.set(points.length);
          this.updateChart(points);
          this.loading.set(false);
        },
        error: () => {
          this.error.set('Не удалось загрузить историю спреда');
          this.loading.set(false);
        },
      });
  }

  private updateChart(points: SpreadHistoryPoint[]): void {
    if (!this.openSpreadSeries || !this.closeSpreadSeries) return;

    const toSec = (ms: number) => Math.floor(ms / 1000) as Time;

    this.openSpreadSeries.setData(
      points.map((p) => ({ time: toSec(p.timestamp), value: p.openSpread })),
    );
    this.closeSpreadSeries.setData(
      points.map((p) => ({ time: toSec(p.timestamp), value: p.closeSpread })),
    );

    this.chart?.timeScale().fitContent();
  }
}

<div
  class="dialog-backdrop"
  (click)="onBackdropClick($event)"
  (keydown)="onBackdropKeydown($event)"
  tabindex="0"
  role="dialog"
  aria-modal="true"
  aria-label="Spread history dialog"
>
  <div class="dialog-content">
    <div class="dialog-header">
      <h2 class="dialog-title">
        История спреда — {{ bot().coin }}
      </h2>
      <button class="btn-close" (click)="close()" aria-label="Закрыть">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M18 6 6 18" />
          <path d="m6 6 12 12" />
        </svg>
      </button>
    </div>

    <div class="dialog-body">
      <div class="chart-legend">
        <div class="legend-item">
          <span class="legend-dot open"></span>
          <span class="legend-text">{{ primaryLabel() }} → {{ secondaryLabel() }}</span>
          <span class="legend-hint">продать {{ primaryLabel() }}, купить {{ secondaryLabel() }}</span>
        </div>
        <div class="legend-item">
          <span class="legend-dot close"></span>
          <span class="legend-text">{{ secondaryLabel() }} → {{ primaryLabel() }}</span>
          <span class="legend-hint">продать {{ secondaryLabel() }}, купить {{ primaryLabel() }}</span>
        </div>
      </div>

      <div class="chart-wrapper">
        @if (loading()) {
          <div class="chart-overlay">
            <span class="placeholder-text">Загрузка данных...</span>
          </div>
        } @else if (error()) {
          <div class="chart-overlay">
            <span class="placeholder-text error">{{ error() }}</span>
          </div>
        }
        <div class="chart-container" #chartContainer></div>
      </div>

      @if (!loading() && !error()) {
        <div class="dialog-footer">
          <span class="point-count">{{ pointCount() }} свечей · 1 мин · ~{{ (pointCount() / 60) | number:'1.0-0' }} ч</span>
        </div>
      }
    </div>
  </div>
</div>
